name: Check naming conventions
on:
  pull_request:

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Validate branch name
        run: |
          # Getting branch name
          branch_name="${GITHUB_HEAD_REF}"

          echo "Checking branch: $branch_name"

          pattern="^(feature|hotfix|fix|chore|issue)\/[0-9]+[-0-9a-zA-Z]*$"

          # Check if the branch name matches the pattern
          if [[ ! "$branch_name" =~ $pattern ]]; then
            echo "Invalid branch name: $branch_name"
            echo "Use format: feature/123, hotfix/456-task, fix/789-bugfix"
            exit 1
          fi
        shell: bash
