name: Check naming conventions
on:
  pull_request:

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Validate branch name
        run: |
          # Getting branch name
          branch_name="${GITHUB_HEAD_REF}"

          echo "Checking branch: $branch_name"

          pattern="^(feature|hotfix|fix|chore|issue)\/[0-9]+[-0-9a-zA-Z]*$"

          # Check if the branch name matches the pattern
          if [[ ! "$branch_name" =~ $pattern ]]; then
            echo "Invalid branch name: $branch_name"
            echo "Use format: feature/123, hotfix/456-task, fix/789-bugfix"
            exit 1
          fi
        shell: bash

      - name: Validate commits messages
        run: |
          # Get commits specific to the PR branch
          commits=$(git log --format=%s origin/${{ github.head_ref }}..HEAD)

          echo "Checking commits"

          pattern="^(feature|hotfix|fix|chore|issue)\/[0-9]+: "

          while read -r commit; do
            # Check if the commit is a merge commit
            if [[ "$commit" == "Merge pull request"* ]]; then
              echo "Skipping merge commit: \"$commit\""
              continue
            fi

            # Validate the message pattern
            if ! [[ $commit =~ $pattern ]]; then
              echo "Invalid commit: \"$commit\"""
              echo "Use format: feature/123: Add some feature"
              exit 1
            fi
          done <<< "$commits"
